#!/bin/bash

# This script just generates the full sources for user visual inspection,
# saving it on the parent folder.
#
#    $ ./gensource
#    ../rules.t2t generated
#    $
#
# If you need to generate the HTML version, just use the original .t2t file
# inside this folder:
#
#    $ txt2tags rules.t2t 
#    txt2tags wrote ../rules.html
#    $

txt2tags --dump-source rules.t2t > ../rules.t2t
echo "../rules.t2t generated"
exit 0
