.TH "TXT2TAGS" 1 "2008年7月" ""

.SH 名称
.P
txt2tags \- 文本格式化及转换工具

.SH 总览
.P
\fBtxt2tags\fR [\fI选项\fR]... [\fI文件\fR]...

.SH 描述
.P
\fBtxt2tags\fR是一个用Python开发的GPL文本格式化及转换工具。
它以最小的开销将单一的文本文件转换为
\fIHTML\fR, \fIXHTML\fR, \fISGML\fR, \fILaTeX\fR, \fILout\fR, \fIMan Page\fR, \fIMoinMoin\fR,
\fIWikipedia\fR, \fIDokuWiki\fR, \fIGoogle Code Wiki\fR, \fIMagicPoint\fR 及 \fIPageMaker\fR
格式的文档。

.P
用户只要知道少量简单的\fBtxt2tags\fR标记，编写纯文本文件即可。
程序会做所有辛苦的工作，加入复杂的标签，
并处理目标文档中的错误。

.P
同一个文本文件可以转换为支持的任一目标格式，不用另外进行编辑。
这也是\fBtxt2tags\fR的目的：
单源，多目标。

.P
请访问程序主页
\fIhttp://txt2tags.sourceforge.net\fR.

.SH 选项
.TP
 \fB\-C\fR, \fB\-\-config\-file\fR
从外部文件中读入配置(效果同 %!includeconf)

.TP
     \fB\-\-css\-sugar\fR
在HTML/XHTML格式的目标文件中插入CSS\-friendly标签

.TP
     \fB\-\-css\-inside\fR
在HTML/XHTML头部插入CSS文件内容

.TP
     \fB\-\-dump\-config\fR
打印找到的所有配置并退出

.TP
     \fB\-\-dump\-source\fR
查看文档源文件，源文件中includes命令包含的文件内容全部展开

.TP
     \fB\-\-encoding\fR
指定目标文件的编码(utf\-8, iso\-8859\-1, 等)

.TP
     \fB\-\-gui\fR
调用Tk图形界面

.TP
 \fB\-h\fR, \fB\-\-help\fR
打印帮助信息并退出

.TP
 \fB\-H\fR, \fB\-\-no\-headers\fR
不显示头部、标题和尾部信息

.TP
     \fB\-\-headers\fR
显示头部、标题和尾部信息(默认 打开)

.TP
 \fB\-i\fR, \fB\-\-infile\fR=\fIFILE\fR
指定输入文件名 FILE ('\-' 表示 标准输入)

.TP
     \fB\-\-mask\-email\fR
隐藏邮件地址(防止垃圾邮件地址收割)：将x@y.z转换为<x (a) y z>

.TP
 \fB\-n\fR, \fB\-\-enum\-title\fR
对所有标题行进行编号：1, 1.1, 1.1.1, 等

.TP
     \fB\-\-no\-dump\-config\fR
不输出配置信息

.TP
     \fB\-\-no\-dump\-source\fR
不输出源文件内容

.TP
     \fB\-\-no\-encoding\fR
清除编码设置

.TP
     \fB\-\-no\-enum\-title\fR
关闭标题自动编号效果

.TP
     \fB\-\-no\-infile\fR
清除所有预设的infile声明

.TP
     \fB\-\-no\-mask\-email\fR
不隐藏邮件地址，关闭 \-\-mask\-email 选项

.TP
     \fB\-\-no\-outfile\fR
清除预设的 outfile 声明

.TP
     \fB\-\-no\-quiet\fR
显示信息，关闭 \-\-quiet 选项

.TP
     \fB\-\-no\-rc\fR
不使用用户配置文件：~/.txt2tagsrc

.TP
     \fB\-\-no\-style\fR
清除文档样式设置

.TP
     \fB\-\-no\-toc\fR
目标文档中不生成目录信息

.TP
     \fB\-\-no\-toc\-only\fR
关闭 \-\-toc\-only 选项

.TP
 \fB\-o\fR, \fB\-\-outfile\fR=\fIFILE\fR
设置输出文件名为 FILE ('\-' 是 标准输出)

.TP
 \fB\-q\fR, \fB\-\-quiet\fR
安静模式，除了出错的信息其他都不显示

.TP
     \fB\-\-rc\fR
使用用户配置文件：~/.txt2tagsrc (默认 打开)

.TP
     \fB\-\-style\fR=\fIFILE\fR
使用 FILE 指定文档样式 (类似 Html CSS)

.TP
\fB\-t\fR, \fB\-\-target\fR=\fITYPE\fR
指定目标文档类型。目前支持：
html, xhtml, sgml, tex, lout, man, mgp, wiki,
gwiki, doku, moin, pm6, txt

.TP
     \fB\-\-toc\fR
生成目标文档时添加目录信息

.TP
     \fB\-\-toc\-level\fR=\fIN\fR
显示的最大目录层次设为 N

.TP
     \fB\-\-toc\-only\fR
打印文档目录并退出

.TP
 \fB\-v\fR, \fB\-\-verbose\fR
文件转换时显示详细的信息

.TP
 \fB\-V\fR, \fB\-\-version\fR
打印程序版本并退出

.P
默认情况下，转换生成的文件以'file.<type>'保存。
使用 \-\-outfile 可以强制指定输出文件名。
如果输入文件置'\-'，则从标准输入(STDIN)中读入。
如果输出文件置'\-'，则输出到标准输出(STDOUT)。

.SH 结构
.P
Txt2tags的源文件可以包含以下三个部分：

.TP
\fB头部\fR
头三行。用于文档声明。
如果不需要指定头部信息，则放空或指定
no\-header选项。

.TP
\fB设置\fR
从第四行开始。所有设置的格式均为%!keyword: value。
也可以在配置文件或命令行中进行设置。

.TP
\fB主体\fR
真正的文档来源！只要有这部分内容就是一个可用的
txt2tags 文件。

.SH 设置
.P
源文件转换的定制有两种不同的方法。
一种是采用外部的配置文件，比如RC文件(~/.txt2tagsrc) 或 用户指定的其它文件。
另一种是在源文件内部使用设置选项直接进行配置。
两种方法采用同样的语法：

.TP
\fB%!target:\fR
设置输出文档类型

.TP
\fB%!options(target):\fR
设置该类型输出文档的相关选项

.TP
\fB%!include: file.t2t\fR
把一个 txt2tags 文件内容直接加入源文档

.TP
\fB%!include: ``file.txt``\fR
把一个文本文件的内容作为原文引用块加入源文档

.TP
\fB%!include: file.html\fR
把一个文件内容不作修改直接加入目标文档

.TP
\fB%!style:\fR
为XHTML和HTML格式的目标文档设置CSS(级联样式表) 或
为TEX格式的目标文件载入 \eusepackage 模块

.TP
\fB%!encoding:\fR
设置字符集(例如 iso\-8859\-1) 解决i18n国际化问题

.TP
\fB%!includeconf:\fR
将外部文件中的配置信息读入当前源文件

.TP
\fB%!guicolors:\fR
设置Tk图形界面的颜色

.TP
\fB%!preproc:\fR
用户定制的宏，
在文本解析之\fB前\fR被执行

.TP
\fB%!postproc:\fR
用户定制的宏，
在文本解析之\fB后\fR被执行

.SS 设置规则
.RS
.IP \(bu 3
设置只在文档中配置部分才起作用，
在文档的主体部分则被视为普通的注释行。
唯一的例外是include命令，它在主体部分仍可用。

.IP \(bu 3
如果在文档中的配置部分出现多个相同关键词的配置，
那么只有最后一个起作用。
有三个例外：options, preproc 和postproc，它们的选项是累加的。

.IP \(bu 3
如果设置行里的关键词不是可用的，
则将此行视为普通的注释行。

.IP \(bu 3
这些设置的优先级高于txt2tagsrc文件，
但低于命令行选项。
.RE

.SH 语法
.P
只需在源文档(纯文本文件)中使用非常简单的标记语法来
标识文档结构及格式。
以下是全部标记列表：

.SS 基础
.nf
  头部                源文件的头三行
  标题                = 文字 =
  带数字编号的标题    + 文字 +
  段落                文字
.fi


.SS 美化
.nf
  粗体                **文字**
  斜体                //文字//
  下划线              __文字__
  删除线              --文字--
  等宽                ``文字``
.fi


.SS 文本块
.nf
  引用                <TAB>文字
  列表                - 条目
  带编号的列表        + 条目
  定义式列表          : 条目
  完全引用行          ``` 内容
  完全引用域          ```<LineBreak> 内容 <LineBreak>```
  原文行              """ 内容
  原文域              """<LineBreak> 内容 <LineBreak>"""
  表格                | 单元1 | 单元2 | 单元3...
.fi


.SS 其他
.nf
  隔离行              -----------------------...
  粗隔离行            =======================...
  链接                [标签 url地址]
  图片                [filename.jpg]
  原始文字            ""内容""
  注释                % 注释内容
.fi


.P
请阅读Txt2tags用户指南(在程序文档目录下)
获知每个标记的详细说明。

.SH 例子
.P
假设你已经写了一个带标记的file.t2t文件，
现在我们开始进行转换。

.TP
\fB转换为HTML文件，保存为 file.html\fR
$ txt2tags \-t html file.t2t

.TP
\fB同上，使用重定向\fR
$ txt2tags \-t html \-o \- file.t2t > file.html

.TP
\fB包含目录信息\fR
$ txt2tags \-t html \-\-toc file.t2t

.TP
\fB包含目录信息，且对每个条目进行编号\fR
$ txt2tags \-t html \-\-toc \-\-enum\-title file.t2t

.TP
\fB快速浏览目录信息\fR
$ txt2tags \-\-toc\-only file.t2t

.TP
\fB从标准输入(STDIN)读入一行进行快速测试\fR
$ (echo ; echo "**bold**") | txt2tags \-t html \-H \-

.SH 宏
.TP
%%date
用于显示当前日期，默认格式为YYYYMMDD(年月日)。
格式是可调的，调整时使用的语法：
%%date(format\-string)

.TP
%%infile
用于得到源文件的信息。
格式是可调的，调整时使用的语法：%%infile(format\-string)

有用的例子：使用尾部链接[查看源文件 %%infile]， 
文件名被改掉的话该链接也会自动更新。

.TP
%%mtime
用于得到源文件的最近修改时间。
采用的格式与%%date宏相同。

.TP
%%outfile
用于得到目标文件的信息。
格式是可调的，调整时使用的语法：%%outfile(format\-string)

有用的例子：使用引用自身的链接"This is the manpage\-zh.man file"，
文件名改掉的话该链接也会自动更新。

.TP
%%toc
%%toc宏指定目录在文档中存放的位置。
你想把它放在文档中哪个位置都可以，
出现一次或多次均可。

注意: %%toc宏只有在设置了\-\-toc选项的情况下才会被展开。

.SH 作者
.P
程序由 Aurelio Marinho Jargas <verde@aurelio.net> 编写并维护。

.P
此手册页原始文本由Jose Inacio Coelho <jic@technologist.com> 编写，
使用\fBtxt2tags\fR转换为man格式。

.P
中文版由 Abby Pan <abbypan@mail.ustc.edu.cn>翻译。

.SH 版权
.P
Copyright (C) 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008 Aurelio Jargas

.P
This is free software; see the source for copying conditions. There is
NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.


.\" man code generated by txt2tags 2.6b (http://txt2tags.sf.net)
.\" cmdline: txt2tags -t man doc/Chinese/manpage-zh.t2t

