.TH "" 1 "" ""

.SH Simple table

.TS
tab(^); lll.
 Cell 1\-1^Cell 1\-2^Cell 1\-3
 Cell 2\-1^Cell 2\-2^Cell 2\-3
 Cell 3\-1^Cell 3\-2^Cell 3\-3
.TE

.SH Simple table + border

.TS
allbox, tab(^); lll.
 Cell 1\-1^Cell 1\-2^Cell 1\-3
 Cell 2\-1^Cell 2\-2^Cell 2\-3
 Cell 3\-1^Cell 3\-2^Cell 3\-3
.TE

.SH Simple table + heading

.TS
tab(^); lll.
 \fBHead 1\-1\fR^\fBHead 1\-2\fR^\fBHead 1\-3\fR
 Cell 1\-1^Cell 1\-2^Cell 1\-3
 Cell 2\-1^Cell 2\-2^Cell 2\-3
 Cell 3\-1^Cell 3\-2^Cell 3\-3
.TE

.SH Simple table + heading + border

.TS
allbox, tab(^); lll.
 \fBHead 1\-1\fR^\fBHead 1\-2\fR^\fBHead 1\-3\fR
 Cell 1\-1^Cell 1\-2^Cell 1\-3
 Cell 2\-1^Cell 2\-2^Cell 2\-3
 Cell 3\-1^Cell 3\-2^Cell 3\-3
.TE

.SH Simple table + heading + border + footer

.TS
allbox, tab(^); lll.
 \fBHead 1\-1\fR^\fBHead 1\-2\fR^\fBHead 1\-3\fR
 Cell 1\-1^Cell 1\-2^Cell 1\-3
 Cell 2\-1^Cell 2\-2^Cell 2\-3
 Cell 3\-1^Cell 3\-2^Cell 3\-3
 \fBFoot 1\-1\fR^\fBFoot 1\-2\fR^\fBFoot 1\-3\fR
.TE

.SH Simple table + heading + border + centralized

.TS
center, allbox, tab(^); lll.
 \fBHead 1\-1\fR^\fBHead 1\-2\fR^\fBHead 1\-3\fR
 Cell 1\-1^Cell 1\-2^Cell 1\-3
 Cell 2\-1^Cell 2\-2^Cell 2\-3
 Cell 3\-1^Cell 3\-2^Cell 3\-3
.TE

.SH Cell alignment

.TS
allbox, tab(^); ll.
 =======^=======
 <^>
 =^=
 >^<
.TE

.SH Heading alignment

.TS
allbox, tab(^); ll.
 \fB=======\fR^\fB=======\fR
 \fB<\fR^\fB>\fR
 \fB=\fR^\fB=\fR
 \fB>\fR^\fB<\fR
.TE

.SH Column span for cells

.TS
allbox, tab(^); llll.
 1^2^3^4
 1^2^3 + 4
 1 + 2 + 3^4
 1^2 + 3^4
 1 + 2 + 3 + 4
.TE

.SH Column span for headings

.TS
allbox, tab(^); llll.
 \fB1\fR^\fB2\fR^\fB3\fR^\fB4\fR
 \fB1\fR^\fB2\fR^\fB3 + 4\fR
 \fB1 + 2 + 3\fR^\fB4\fR
 \fB1\fR^\fB2 + 3\fR^\fB4\fR
 \fB1 + 2 + 3 + 4\fR
.TE

.SH Cell alignment + column span

.TS
allbox, tab(^); lll.
 =======^=======^=======
 <^=
 =
 =^>
.TE

.SH Heading alignment + column span

.TS
allbox, tab(^); lll.
 \fB=======\fR^\fB=======\fR^\fB=======\fR
 \fB<\fR^\fB=\fR
 \fB=\fR
 \fB=\fR^\fB>\fR
.TE

.SH Some empty cells

.TS
allbox, tab(^); lllll.
 A^B^C^D^
 F^G^H^^J
 K^L^^N^O
 P^^R^S^T
 ^V^W^X^Y
.TE

.SH Lines with different number of cells, increase

.TS
allbox, tab(^); l.
 1
 1^2
 1^2^3
 1^2^3^4
 1^2^3^4^5
.TE

.SH Lines with different number of cells, decrease

.TS
allbox, tab(^); lllll.
 1^2^3^4^5
 1^2^3^4
 1^2^3
 1^2
 1
.TE

.SH One cell table

.TS
tab(^); l.
 Cell 1
.TE

.SH One cell table + border

.TS
allbox, tab(^); l.
 Cell 1
.TE

.SH One cell table + heading

.TS
tab(^); l.
 \fBHead 1\fR
.TE

.SH One cell table + heading + border

.TS
allbox, tab(^); l.
 \fBHead 1\fR
.TE

.SH Empty lines

.TS
allbox, tab(^); l.
 
 
 
.TE

.\" man code generated by txt2tags (http://txt2tags.org)
.\" cmdline: txt2tags -q --no-rc -i table.t2t -t man
