# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-WikiConverter-Txt2tags
version:      0.03
version_from: lib/HTML/WikiConverter/Txt2tags.pm
installdirs:  site
requires:
    HTML::WikiConverter:           0.68
#    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
