<?php

/**
 * @file
 * Provides a Txt2tags input filter.
 * Based on markdown input filter.
 */

/**
 * Implements hook_help().
 */
 
$T2TVersion = "20121206";

function txt2tags_help($path, $arg) {
  switch ($path) {
    case 'admin/help#txt2tags':
      return t('<p>The Txt2tags filter allows you to enter content using <a href="http://www.txt2tags.org/">Txt2tags</a>, a simple plain-text syntax that is transformed into valid XHTML.</p>');
  }
}

/**
 * Implements hook_filter_info().
 */
function txt2tags_filter_info() {
  $filters['filter_txt2tags'] = array(
    'title' => t('Txt2tags'),
    'description' => t('Allows content to be submitted using Txt2tags, a simple plain-text syntax that is filtered into valid XHTML.'),
    'process callback' => '_filter_txt2tags',
    'settings callback' => '_filter_txt2tags_settings',
    'tips callback'  => '_filter_txt2tags_tips',
  );

  return $filters;
}

/**
 * Returns the txt2tags input filter tips.
 * @TODO: make it easier for translators.
 */
function _filter_txt2tags_tips($format, $long = FALSE) {
  if ($long) {
    return t('Quick Tips:<ul>
      <li>Double returns = Paragraph</li>
      <li>**Double** stars = <b>Bold</b></li>
      <li>//Double// slash = <i>Italic</i></li>
      <li>__Double__ underline = <u>Underline</u></li>
      <li>--Double-- dash = <s>Strike through</s></li>
      <li>This is [a link http://www.txt2tags.org]</li>
      <li>- Start a list with a dash</li>
      <li>+ Start a numbered list with a plus</li>
      <li>== Heading level 2 ==</li>
      <li>=== Heading level 3 ===</li>
      </ul>For complete details on the Txt2tags syntax, see the <a href="http://www.txt2tags.org/markup.html">Txt2tags documentation</a>.');
  }
  else {
    return t('You can use <a href="@filter_tips">Txt2tags syntax</a> to format and style the text. Also see <a href="@txt2tags_website">Txt2tags markup help</a> for more.', array('@filter_tips' => url('filter/tips'), '@txt2tags_website' => 'http://www.txt2tags.org/markup.html'));
  }
}

/**
 * Implements hook_block_view().
 */
function txt2tags_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'txt2tags_help':
      $block['title'] = t('Txt2tags filter tips');
      $block['content'] = _txt2tags_help_block();
      break;
  }

  return $block;
}

/**
 * Implements hook_block_info().
 */
function txt2tags_block_info() {
  $blocks = array();
  $blocks['txt2tags_help'] = array(
    'info' => t('Txt2tags filter tips'),
  );

  return $blocks;
}

/**
 * Provides content for the txt2tags help block.
 */
function _txt2tags_help_block() {
  return '<pre>' . t("
== Header 2 ==
=== Header 3 ===
==== Header 4 ====
===== Header 5 =====

[Link http://txt2tags.org]

Inline markup like //italics//, __underline__, --strike--, 
 **bold**, and ``code``.

``` Blockquote. 



- Bullet lists are easy too
- Another one
- Another one

+ A numbered list
+ Which is numbered

") . '</pre>';
}

/**
 * Filter process callback.
 */
function _filter_txt2tags($text, $format) {
  if (!empty($text)) {
    module_load_include('php', 'txt2tags', 'txt2tags');
    
    $x = new T2T($text);
	$x->go();
	$text = $x->bodyhtml;
		
  }

  return $text;
}

/**
 * Filter settings callback. Just provides a version overview.
 */
function _filter_txt2tags_settings($form, &$form_state, $filter, $format, $defaults) {
  module_load_include('php', 'txt2tags', 'txt2tags');

  $settings['txt2tags_wrapper'] = array(
    '#type' => 'fieldset',
    '#title' => t('Txt2tags'),
  );
  $links = array(
    'Txt2tags PHP Version: <a href="http://www.txt2tags.org/txt2tags.form.php">20121206</a>',
  );
  $settings['txt2tags_wrapper']['txt2tags_status'] = array(
    '#title' => t('Versions'),
    '#type' => 'item',
    '#markup' => theme('item_list', array('items' => $links)),
  );

  return $settings;
}
