.TH "TXT2TAGS" 1 "May, 2005" ""

.SH NOMBRE
.P
txt2tags \- Herramienta de formateo y conversión de texto

.SH SINOPSIS
.P
\fBtxt2tags\fR [\fIOPCIÓN\fR]... [\fIARCHIVO\fR]...

.SH DESCRIPCIÓN
.P
\fBtxt2tags\fR es una herramienta GLP de conversión de formatos, escrita en Pyton, que
genera documentos \fIHTML\fR, \fIXHTML\fR, \fISGML\fR, \fILaTeX\fR, \fILout\fR,
\fIMan Page\fR, \fIMoinMoin\fR, \fIMagicPoint\fR y \fIPageMaker\fR a partir de un simple
archivo de texto mínimamente marcado ( p.ej.: texto plano).

.P
El usuario sólo precisa conocer unas pocas y sencillas reglas de marcado, propias de  de \fBtxt2tags\fR, 
y escribir sus archivos en texto plano. El programa se encarga de realizar todo el trabajo, añadiendo las marcas necesarias y 
arreglándose con los problemas que pueda presentar el archivo de salida.

.P
El mismo archivo de texto puede ser convertido a todos y cada uno de los formatos de salida,
sin necesidad de tener que editarlo cada vez. Éste es el propósito de \fBtxt2tags\fR : UN archivo fuente, MÚLTIPLES archivos finales.

.P
Visitad la página del programa, que se encuentra en:
\fIhttp://txt2tags.sourceforge.net\fR.

.SH OPCIONES
.TP
 \fB\-C\fR, \fB\-\-config\-file\fR
Lee la configuración desde un archivo externo (actúa cómo %!includeconf)

.TP
     \fB\-\-css\-sugar\fR
Inserta CSS\-friendly tags para archivos de salida HTML y XHTML 

.TP
     \fB\-\-css\-inside\fR
Inserta el contenido de un archivo CSS en el encabezamiento HTML/XHTML 

.TP
     \fB\-\-dump\-config\fR
Imprime toda la configuración encontrada y sále.

.TP
     \fB\-\-dump\-source\fR
Imprime el documento fuente, con las inclusiones expandidas

.TP
     \fB\-\-encoding\fR
Elige la codificación del archivo de salida (UTF\-8, ISO\-8859\-1, etc)

.TP
     \fB\-\-gui\fR
Lanza la Interfaz Gráfica TK

.TP
 \fB\-h\fR, \fB\-\-help\fR
Imprime la información de ayuda y sále

.TP
 \fB\-H\fR, \fB\-\-no\-headers\fR
Suprime el encabezamiento, título y pié de página

.TP
     \fB\-\-headers\fR
Muestra el encabezamiento, título y pié de página (por defecto, ON)

.TP
 \fB\-i\fR, \fB\-\-infile\fR=\fIFILE\fR
Toma FILE como nombre del archivo de entrada ('\-' para STDIN)

.TP
     \fB\-\-mask\-email\fR
Oculta email a los robots de spam. < x@y.z > se convierte en  < x (a) y z >

.TP
 \fB\-n\fR, \fB\-\-enum\-title\fR
Numera todos los títulos: 1, 1.1, 1.1.1, etc

.TP
     \fB\-\-no\-dump\-config\fR
Desactiva dump config

.TP
     \fB\-\-no\-dump\-source\fR
Desactiva dump source 

.TP
     \fB\-\-no\-encoding\fR
Excluye la configuración de encoding

.TP
     \fB\-\-no\-enum\-title\fR
Desactiva la numeración de títulos

.TP
     \fB\-\-no\-infile\fR
Suprime las anteriores declaraciones infile

.TP
     \fB\-\-no\-mask\-email\fR
Muestra emails. Desactiva la opción \-\-mask\-email 

.TP
     \fB\-\-no\-outfile\fR
Suprime las anteriores declaraciones outfile

.TP
     \fB\-\-no\-quiet\fR
Muestra mensajes. Desactiva la opción \-\-quiet 

.TP
     \fB\-\-no\-rc\fR
No lee el archivo de configuración de usuario ~/.txt2tagsrc

.TP
     \fB\-\-no\-style\fR
Suprime la declaración de estilo

.TP
     \fB\-\-no\-toc\fR
No añade índice de contenidos TOC (Table of Contents) al documento final

.TP
     \fB\-\-no\-toc\-only\fR
Desactiva la opción \-\-toc\-only 

.TP
 \fB\-o\fR, \fB\-\-outfile\fR=\fIFILE\fR
Toma FILE como el nombre del archivo de salida ('\-' para STDOUT)

.TP
 \fB\-q\fR, \fB\-\-quiet\fR
Modo silencioso, suprime todas las salidas (excepto errores)

.TP
     \fB\-\-rc\fR
Lee el archivo de configuracion de usuario ~/.txt2tagsrc (por defecto, ON)

.TP
     \fB\-\-style\fR=\fIFILE\fR
Usa FILE como documento de estilo (cómo HTML CSS)

.TP
\fB\-t\fR, \fB\-\-target\fR
Define el tipo de documento final. Actualmente las opciones son:
html, xhtml, sgml, tex, lout, man, mgp, moin, pm6, txt

.TP
     \fB\-\-toc\fR
Añade índice de contenidos, TOC (Table of Contents) al documento final

.TP
     \fB\-\-toc\-level\fR=\fIN\fR
Define en N el nivel máximo (profundidad) del índice de contenidos

.TP
     \fB\-\-toc\-only\fR
Imprime el índice de contenidos (TOC) y sále

.TP
 \fB\-v\fR, \fB\-\-verbose\fR
Imprime los mensajes de información durante la conversión

.TP
 \fB\-V\fR, \fB\-\-version\fR
Imprime la versión del programa y sále

.P
Por defecto, el archivo de salida es salvado en 'file.<type>'.
Usar \-\-outfile para forzar un nombre de archivo de salida.
Si el archivo de entrada es '\-', lee de STDIN.
Si el archivo de salida es '\-', vuelca el archivo de salida en STDOUT.

.SH ESTRUCTURA
.P
Un archivo fuente txt2tags puede tener tres áreas:

.TP
\fBEncabezamiento\fR
Las tres primeras líneas. Son usadas para la identificación del documento.
Si no precisas encabezamientos, puedes dejar en blanco la primera línea o mediante la
opción  no\-header .

.TP
\fBConfiguraciones\fR
Se inician a partir de la cuarta línea. Todas las configuraciones siguen el formato: \fB%!clave: valor\fR.
Las configuraciones también pueden hacerse mediante archivos de configuración o línea de comandos.

.TP
\fBCuerpo\fR
Es el documento en si. Es la única área imprescindible para tener un archivo txt2tags válido.

.SH CONFIGURACIÓN
.P
La conversión de un archivo fuente puede personalizarse por dos vias: externa o interna.
Externamente, las configuraciones pueden ser tomadas de un archivo RC
(~/.txt2tagsrc) o importadas de otro archivo de configuración definido por el usuario. Internamente,
la personalización se realiza mediante comandos de configuración especiales en el mismo documento fuente.
En ambos métodos se utiliza la misma sintaxis:

.TP
\fB%!target:\fR
Define el formato destino (target) principal

.TP
\fB%!options(target):\fR
Define las opciones de cada destino

.TP
\fB%!include: file.t2t\fR
Incluye un archivo txt2tags en el documento

.TP
\fB%!include: ``file.txt``\fR
Incluye un archivo de texto (verbatim) en el documento

.TP
\fB%!include: file.html\fR
Incluye un archivo de forma "literal" en el documento, eso és, "tal cómo está"

.TP
\fB%!style:\fR
Define un archivo CSS (Cascading Style Sheets) para archivos finales del tipo XHTML y HTML
o para cargar los módulos (\eusepackage) en un archivo destino tipo TEX

.TP
\fB%!encoding:\fR
Para elegir la codificación de carácteres del archivo final (como ISO\-8859\-1) para usuarios de lengua no\-inglesa

.TP
\fB%!includeconf:\fR
Usado para incluir, el en archivo corriente, una configuración a partir de un archivo externo.

.TP
\fB%!guicolors:\fR
Configuración de los colores para la interfaz GUI (tk/tcl) 

.TP
\fB%!preproc:\fR
Para definir los propios filtros (macros) que serán procesados \fBANTES\fR de procesar el documento

.TP
\fB%!postproc:\fR
Para definir los propios filtros (macros) que serán procesados \fBDESPUÉS\fR de procesar el documento

.SS REGLAS DE LAS CONFIGURACIONES
.RS
.IP \(bu 3
Las configuraciones son sólo vàlidas en el Área de Configuración 
y serán consideradas comentarios si se encuentran en el Área del Cuerpo
. Una excepción es include, que es válida en el Cuerpo.

.IP \(bu 3
Si aparece la misma palabra clave más de una vez en una misma Área de Configuración,
la última hallada será la que se utilizará. Excepciones: options, preproc, postproc, que son acumulativas.
.RE

.RS
.IP \(bu 3
Una línea de configuración con una palabra clave inválida, será considerada un comentario.

.IP \(bu 3
Éstas configuraciones tienen precedencia sobre el archivo txt2tagsrc, pero no sobre las opciones en línea de comando.
.RE

.SH SINTAXIS
.P
Se utiliza una sencilla sintaxis de marcas en el archivo fuente ( el archivo de texto plano) para identificar las estructuras y el formato. Ésta es la lista completa:

.SS Básicas
.nf
  Encabezamiento      Las primeras 3 líneas del archivo fuente
  Título             = palabras =
  Título numerado    + palabras +
  Párrafo            palabras
.fi


.SS Modificadores de Fuentes
.nf
  Negrita             **palabras**
  Italic (cursiva)    //palabras//
  Subrayado           __palabras__
  Monoespaciado       ``palabras``
.fi


.SS Bloques de Texto
.nf
  Cita                  <TAB>palabras
  Lista                 - palabras
  Lista numerada        + palabras
  Lista de definición   : palabras
  Línea verbatim        ``` palabras
  Zona verbatim         ```<Retono (/n)> lìneas <Retorno (/n)>```
  Línea raw             """ palabras
  Zona raw              """<Retorno (/n)> lines <Retorno (/n)>"""
  Tabla                 | celda1 | celda2 | celda3...
.fi


.SS Otras
.nf
  Línea de separación    -----------------------...
  Línea gruesa           =======================...
  Enlaces (links)        [etiqueta url]
  Imagen                 [archivo.jpg]
  Texto raw              ""palabras""
  Comentario             % comentarios
.fi


.P
Leer la Guía del Usuario de txt2tags para una descripción mas detallada de cada marca

.SH EJEMPLOS
.P
Asumiendo que hayas creado el archivo marcado file.t2t, veamos cómo operar para proceder a su conversión:

.TP
\fBConvertir a HTML  (archivo final: file.html)\fR
$ txt2tags \-t html file.t2t

.TP
\fBLo mismo, usando redireccionamiento\fR
$ txt2tags \-t html \-o \- file.t2t > file.html

.TP
\fBIncluyendo un Índice de Contenidos (TOC)\fR
$ txt2tags \-t html \-\-toc file.t2t

.TP
\fBIncluyendo TOC y títulos numerados\fR
$ txt2tags \-t html \-\-toc \-\-enum\-title file.t2t

.TP
\fBVista rápida del Índice de Contenidos\fR
$ txt2tags \-\-toc\-only file.t2t

.TP
\fBComprobación on\-line rápida através de STDIN\fR
$ (echo ; echo "**bold**") | txt2tags \-t html \-H \-

.TP
\fBUtilización de la interfaz gráfica\fR
$ txt2tags \-\-gui file.t2t

.SH TRUCOS
.P
Existen algunos trucos que hacen de \fBtext2tags\fR una excelente herramienta para el tratamiento de documentos:

.P
Anclas

.P
Los títulos pueden tener enlaces con anclas, lo que nos permitira llegar directamente a ellos, 
si el formato del documento final lo permite:

.nf
  Título             = palabras =[ancla]
  Título numerado   + palabras +[ancla]
.fi

.P
Archivos múltiples

.P
\fBtxt2tags\fR puede convertir a más de un archivo a la vez : 

.nf
  txt2tags *.t2t
.fi


.SH MACROS
.TP
%%date
Permite incluir la fecha en curso, en el formato YYYYMMDD. Puede definirse un formato opcional utilizando la sintaxis:
%%date(cadena\-formato) 

.TP
%%infile
Utilizado para obtener información sobre el fichero fuente. Admite formatos opcionales especificados por la sintaxis:  %%infile(cadena\-formato) .

Útil como enlace a pié de página cómo [Ver archivo fuente %%infile], de este modo podrás cambiar el nombre del archivo
y la refencia será actualizada.

.TP
%%mtime

Nos da información sobre la fecha de modificación del archivo fuente. Utiliza el mismo formato que la macro   %%date.

.TP
%%outfile
Utilizado para obtener información sobre el archivo convertido. Admite formatos opcionales utilizando la sintaxis:  %%outfile(cadena\-formato) 

Útil para indicar cosas como: "Este es el archivo de salida  manpage\-es.man ",
Podemos cambiar el nombre del archivo y su referéncia sera actualizada .

.TP
%%toc
%%toc  especifica donde se emplaza el Índice de matérias (TOC).
Puede situarse en cualquier lugar del documento.

NOTE: %%toc sólo sera procesada con la opción \-\-toc .

.SH AUTOR
.P
Escrito y mantenido por Aurelio Jargas <verde@aurelio.net>

.P
Éste Manual fué escrito por Jose Inacio Coelho <jic@technologist.com>
como un fichero de texto, y convertido al formato man por \fBtxt2tags\fR!

.P
La traducción al español fué realizada por Antoni Serra Devecchi <antoni.serra@gmail.com> 

.SH COPYRIGHT
.P
Copyright (C) 2001, 2002, 2003, 2004, 2005 Aurelio Jargas

.P
This is free software; see the source for copying conditions. There is
NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.


.\" man code generated by txt2tags 2.6b (http://txt2tags.sf.net)
.\" cmdline: txt2tags -t man doc/Spanish/manpage-es.t2t

