<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
<HEAD>
<meta name="author" content="Aurelio Jargas www.aurelio.net">
<META NAME="generator" CONTENT="http://txt2tags.org">
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<LINK REL="stylesheet" TYPE="text/css" HREF="inc/site.css">
<LINK REL="stylesheet" TYPE="text/css" HREF="online.css">
<TITLE>txt2tags online</TITLE>
<link rel="icon" type="image/png" href="/favicon.png">
</HEAD>
<BODY id="online">

<DIV CLASS="header" ID="header">
<h1><a href="/">txt2tags</a></h1>
<H3>Free online conversion</H3>
</DIV>

<DIV CLASS="body" ID="body">
<div id="sidebar">
Hot
  <ul>
  <li id="menuonline"><a href="./online.php">Txt2tags Online</a></li>
  <li id="menumarkup"><a href="./markup.html">Markup Demo</a></li>
  </ul>
About
  <ul>
  <!-- <li id="menuhome"><a href="/">Home</a></li> -->
  <li id="menufeatures"><a href="./features.html">Features</a></li>
  <li id="menusample"><a href="./sample.html">Example</a></li>
  <li id="menushots"><a href="./shots.html">Screenshots</a></li>
  <li id="menudocs"><a href="./docs.html">Documentation</a></li>
  <li id="menutips"><a href="./tips.html">Tips &amp; Tricks</a></li>
<!--
  <li id="menuoldnews"><a href="./misc/oldnews.html">Old News</a></li>
-->
  </ul>
Code
  <ul>
  <li id="menudownload"><a href="./download.html">Download</a></li>
  <li id="menuchangelog"><a href="./changelog.html">Changelog</a></li>
  <li id="menutools"><a href="./tools.html">Tools</a></li>
  <li><a href="http://bugs.txt2tags.org">Bug tracker</a></li>
  <li><a href="http://svn.txt2tags.org">SVN</a></li>
  </ul>
Community
  <ul>
  <li id="menuwiki"><a href="http://wiki.txt2tags.org">Wiki</a></li>
  <li id="menublog"><a href="http://txt2tags.wordpress.com">Blog</a></li>
  <li id="menuteam"><a href="./team/index.html">The Team</a></li>
  <li id="menuchildren"><a href="./children.html">The Children</a></li>
  <li id="menucomments"><a href="http://txt2tags.wordpress.com/user-comments/">User Comments</a></li>
  <li id="menuart"><a href="./art.html">Artwork</a></li>
  </ul>
Social
  <ul>
  <li id="menuml"><a href="./ml.html">Mailing List</a></li>
  <li><a href="http://www.facebook.com/pages/txt2tags/335201827209">Facebook</a></li>
  <li><a href="http://twitter.com/aureliojargas">twitter</a></li>
  <!-- <li><a href="http://www.orkut.com.br/Main#Community?cmm=87935">Orkut</a></li> -->
  <li><a href="http://identi.ca/group/txt2tags">identi.ca</a></li>
  </ul>

<P>
<A HREF="https://www.paypal.com/cgi-bin/webscr?cmd=_xclick&amp;business=verde%40aurelio%2enet&amp;item_name=txt2tags%20donation&amp;no_shipping=1&amp;return=http%3a%2f%2faurelio%2enet%2fdonate%2dthanks%2ehtml&amp;cn=&amp;tax=0&amp;currency_code=USD&amp;bn=PP%2dDonationsBF&amp;charset=UTF%2d8"><IMG ALIGN="middle" SRC="img/donate.png" BORDER="0" alt="DONATE"></A>
</P>
</div>

<H2>Txt2tags Online</H2>

<UL>
<LI>Play with txt2tags even before downloading it.
<P></P>
<LI>You can alter the text source or type/paste your own.
<P></P>
<LI>The <A HREF="online.phps">PHP sources</A> are available, you can customize it
 and use on your intranet.
</UL>

<?php require("online.phps"); ?>
</div><div id="footer">
<P>
<IMG ALIGN="middle" SRC="img/t2tpowered-white.png" BORDER="0" ALT="">
</P>
<a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-sa/3.0/80x15.png"></a>
<P>
Last modified on 30 March 2012 at 12:34
(<A HREF="online.t2t">See sources</A>,
<A HREF="http://validator.w3.org/check?uri=referer">Validate HTML</A>)
</P>
</div><div id="fake">
<!-- Google Analytics code -->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-280222-14']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</DIV>

<!-- html code generated by txt2tags 2.6.641 (http://txt2tags.org) -->
<!-- cmdline: txt2tags online.t2t -->
</BODY></HTML>
