.TH "TXT2TAGS" 1 "Abu, 2010" ""


.SH IZENA

.P
txt2tags \- testu formateatze eta bihurtze tresna

.SH SINOPSIA

.P
\fBtxt2tags\fR [\fIaukerak\fR] [\fIFITXATEGIA\fR...]

.SH DESKRIBAPENA

.P
\fBtxt2tags\fR markatze minimoa duen testu fitxategi bat irakurri eta ondoko
helburuetara bihurtzen du:
\fIASCII Art\fR,
\fIAsciiDoc\fR,
\fICreole\fR,
\fIDocBook\fR,
\fIDokuWiki\fR,
\fIEskuliburu Orria (man)\fR,
\fIGoogle Code Wiki\fR,
\fIHTML\fR,
\fILaTeX\fR,
\fILout\fR,
\fIMagicPoint\fR,
\fIMoinMoin\fR,
\fIPageMaker\fR,
\fIPmWiki\fR,
\fISGML\fR,
\fITestu Soila\fR,
\fIWikipedia\fR eta
\fIXHTML\fR.

.P
Eskuliburu orri hau \fBtxt2tags\fR\-ek sortua da testu fitxategi soil batetik.
Testu fitxategi bera HTML\-ra bihurtu da eskuliburuaren sareko bertsiorako.

.P
Iturburu BAT, helburu ASKO \- http://txt2tags.org

.SH SINTAXIA

.nf
Goiburukoak               Iturburu fitxategiaren lehenbizko 3 lerroak
Izenburua                = hitzak =
Zenbakitutako izenburua  + hitzak +
Iruzkina                 % iruzkinak
Lerro bereizlea          -----------------------...
Lerro lodia              =======================...
Irudia                   [fitxategia.jpg]
Estekak                  [etiketa url]

Lodia                    **hitzak**
Etzana                   //hitzak//
Azpimarratuta            __hitzak__
Marratua                 --hitzak--
Tarte bakarrekoa         ``hitzak``
Testu gordina            ""hitzak""
Etiketatua               ''hitzak''

Paragrafoa                hitzak
Aipamena                 <TAB>hitzak
Zerrenda                 - hitzak
Zenbakitutako zerrenda   + hitzak
Definizioen zerrenda     : hitzak
Taula                    | gelaxka1 | gelaxka2 | gelaxka3...

Hitzez hitzeko lerroa    ``` hitzak
Lerro gordina            """ hitzak
Etiketatutako lerroa     ''' hitzak

Hitzez hitzeko area      ```
                         lerroak
                         ```
Area gordina             """
                         lerroak
                         """
Area etiketatua          '''
                         lerroak
                         '''
.fi


.SH AUKERAK

.TP
     \fB\-\-art\-chars\fR=\fIPATROIA\fR
ASCII Art apainketarako erabiliko diren karaktereak definitzeko \fIPATROIA\fR ezarri, ondoko ordenean: Erpina, ertza, aldea, barra1, barra2, maila2, maila3, maila4, maila5. Defektuzko patroia +\-|\-==\-^" da. Aukera hau ASCII Art helbururako erabiltzeen da bakarrik.

.TP
 \fB\-C\fR, \fB\-\-config\-file\fR=\fIFITXATEGIA\fR
Konfigurazioa kanpoko \fIFITXATEGIA\fR fitxategitik irakurri. Konfigurazioak \fI%!gakoa:balioa\fR formatua izan behar du. EZARPENAK atala ikusi xehetasunentzako.

.TP
     \fB\-\-css\-sugar\fR
CSS\-rekin jatorrak diren etiketak txertatu. HTML eta XHTML helburuen kodea CSS fitxategiekin erabiltzeko hobetzen du. Etiketen atributuak kentzen dira, aurkezpen etiketak sahiesten dira, goiburukoak H1, H2 eta H3 etiketekin egiten dira, eta DIV berriak sortzen dira: \fI#header\fR, \fI#body\fR, \fI.toc\fR.

.TP
     \fB\-\-css\-inside\fR
CSS fitxategiaren edukiak HTML/XHTML goiburuetan txertatu. \-\-style erabili CSS fitxategia zehazteko.

.TP
     \fB\-\-dump\-config\fR
Topatutako konfigurazio guztia inprimatu eta irten.

.TP
     \fB\-\-dump\-source\fR
Dokumentuaren iturburua inprimatu, barneratzeko (%!include) guztiak txertatuta.

.TP
     \fB\-\-encoding\fR=\fIKODEKETA\fR
Iturburu fitxategian erabiltzen den karaktere kodeketa \fIKODEKETA\fR\-ra ezarri. Adibidez UTF\-8 edo iso\-8859\-1.

.TP
     \fB\-\-gui\fR
Tk Interfaze Grafikoa abiatu.

.TP
 \fB\-h\fR, \fB\-\-help\fR
Laguntza mezua inprimatu eta irten.

.TP
 \fB\-H\fR, \fB\-\-no\-headers\fR
Goiburukoa eta oinaren informazioa helburutik kendu. Edukia (gorputza) bakarrik ikusiko da.

.TP
     \fB\-\-headers\fR
Goiburukoa eta oinaren informazioa helburuan erakutsi. Defektuz gaituta.

.TP
     \fB\-\-height\fR=\fIZENB\fR
Irteeraren altuera \fIZENB\fR zutabeetan finkatu. Aukera hau ASCII ART helburuarekin bakarrik erabiltzen da, \-\-slides baita erabiltzen bada.

.TP
 \fB\-i\fR, \fB\-\-infile\fR=\fIFITX\fR
FITX zehaztu sarrera fitxategi bezela, iturburu dokumentua.  '\-' erabili iiturburuak STDIN\-etik irakurtzeko.

.TP
     \fB\-\-mask\-email\fR
Epostak spam robotengandik ezkutatu. @ eta puntuak kentzen ditu.  foo@bar.com helbidea <foo (a) bar com> bihurtzen du.

.TP
 \fB\-n\fR, \fB\-\-enum\-title\fR
Gaitu izenburuen zenbakitze automatikoa. Aurrizki moduan 1, 1.1, 1.1.1, ...  erabiliko dira.

.TP
     \fB\-\-no\-dump\-config\fR
\-\-dump\-config aukera ezgaitzen du.

.TP
     \fB\-\-no\-dump\-source\fR
\-\-dump\-source aukera ezgaitzen du.

.TP
     \fB\-\-no\-encoding\fR
Kodeketaren ezarpena garbitu.

.TP
     \fB\-\-no\-enum\-title\fR
Izenburuen zenbakitze automatikoa ezgaitu.

.TP
     \fB\-\-no\-infile\fR
Aurreko infile guztiak kendu.

.TP
     \fB\-\-no\-targets\fR
\-\-targets aukera ezgaitzen du.

.TP
     \fB\-\-no\-mask\-email\fR
Epostaz izkutatzea ezgaitu.

.TP
     \fB\-\-no\-outfile\fR
Aurreko outfile guztiak kendu.

.TP
     \fB\-\-no\-quiet\fR
Mezuak erakutsi, \-\-quiet aukera ezgaituz.

.TP
     \fB\-\-no\-rc\fR
Ez irakurri ~/.txt2tagsrc erabiltzailearen konfigurazio fitxategia.

.TP
     \fB\-\-no\-slides\fR
Diapositibak ezgaitu.

.TP
     \fB\-\-no\-style\fR
Estilo ezarpenak garbitu.

.TP
     \fB\-\-no\-toc\fR
Helburuan Edukien Taula kendu.

.TP
     \fB\-\-no\-toc\-only\fR
\-\-toc\-only aukera ezgaitzen du.

.TP
 \fB\-o\fR, \fB\-\-outfile\fR=\fIFITX\fR
FITX zehaztu irteera fitxategiaren izen bezala. '\-' erabili helbura STDOUT\-era bidaltzeko.

.TP
 \fB\-q\fR, \fB\-\-quiet\fR
Modu geldia. Irteera mezurik ez, erroreak ezik.

.TP
     \fB\-\-rc\fR
Erabiltzailearen ~/.txt2tagsrc konfigurazio fitxategia irakurri. Defektuz gaituta.

.TP
     \fB\-\-slides\fR
Irteera aurkezpen diapositiba bezala formateatu. Aukera hau ASCII Art helburuarekin bakarrik erabiltzen da.

.TP
     \fB\-\-style\fR=\fIFITX\fR
FITX erabili dokumentuaren estilo moduan. HTML/XHTML dokumentuen CSS fitxategiak edo LaTeX paketeak definitzeko erabilia. Aukera hau askotan erabili daiteke fitxategi bat baino gehiago sartzeko.

.TP
\fB\-t\fR, \fB\-\-target\fR=\fIMOTA\fR
Helburuko dokumentuaren mota \fIMOTA\fR\-ra ezarri. Gehien erabilitako helburuak: \fIhtml\fR, \fIxhtml\fR, \fItex\fR, \fIman\fR, \fItxt\fR. \-\-targtets aukera erabili eskuragarri dauden helburu guztiak ikusteko.

.TP
     \fB\-\-targets\fR
Eskuragarri dauden helburu guztiak erakutsi eta irten.

.TP
     \fB\-\-toc\fR
Edukien Taula (TOC) automatiko gehitu helburu dokumentura, Goiburukoa eta Gorputzaren artean. TOC\-aren kokapena %%TOC makroarekin zehaztu dezakezu.

.TP
     \fB\-\-toc\-level\fR=\fIZENB\fR
Edukien Taularen maila (sakonera) maximoa \fIZENB\fR\-en ezarri. \fIZENB\fR baino sakonago dauden izenburuak ez dira Edukin Taulan sartuko.

.TP
     \fB\-\-toc\-only\fR
Dokumentuaren Edukien Taula inprimatu eta irten.

.TP
 \fB\-v\fR, \fB\-\-verbose\fR
Bihurketaren bitartean mezu informatiboak inprimatu. Aukera hau behin baino gehiago erabili daiteke jasotako mezu kopurua handitzeko.

.TP
 \fB\-V\fR, \fB\-\-version\fR
Programaren bertsioa inprimatu eta irten.

.TP
     \fB\-\-width\fR=\fIZENB\fR
Irteeraren zabalera \fIZENB\fR zutabeetan finkatu. Aukera hau ASCII Art helburuarekin bakarrik erabiltzen da.

.SH ITURBURU FITXATEGIAK

.P
Iturburu fitxategiak gehienetan \fI.t2t\fR luzapenarekin identifikatzen dira (nirefitx.t2t adibidez).
Zure iturburuak hiru area eduki ditzake:

.TP
\fBGoiburukoa\fR (aukerakoa)
Fitxategiaren lehenbiziko hiru lerroak. Zuriz hutsi behar ez badituzu. Dokumentuaren izenburu, egile, bertsio eta datarentzako erabilita.

.TP
\fBEzarpenak\fR (aukerakoa)
Goiburukoaren ondoren hasten da (4. edo 2. lerroa) eta Gorputza hasten denean bukatzen da. Konfiguraziorako erabiltzen da, %!gakoa: balioa formatuan.

.TP
\fBGorputza\fR
Goiburukoaren ondoren, baliozko lehenbiziko lerroan hasten da (iruzkin edo
ezarpena ez dena) eta dokumentu bukaerarekin amaitzen da. Dokumentuaren
edukientzakoe erabiltzen da.

.SH EZARPENAK

.P
Ezarpenek, aukeren antzera, \fBtxt2tags\fR pertsonalizatzea ahalbidetzen dute. Hiru lekutan erabil daitezke: iturburu dokumentuaren Ezarpenak arean, ~/.txt2tagsrc fitxategian, \-\-config\-\-file aukerarekin zehaztutako kanpoko fitxategi batean.

.TP
\fB%!target\fR
Helburu formatua ezartzen du, \-\-target\-ekin bezala. Adibidez:
.nf
%!target: html
.fi



.TP
\fB%!options(target)\fR
Helburu bakoitzerako aukera lehenetsiak zehazten ditu. Komando lerroko aukerak erabili behar dituzu. Adibidez:
.nf
%!options(html): --toc --toc-level 3 --css-sugar
.fi



.TP
\fB%!includeconf\fR
Kanpoko fitxategi batetik unekoan ezarpenak txertatzen du, \-\-config\-file\-k bezala. Adibidez:
.nf
%!includeconf: nirekonfigurazioa.t2t
.fi



.TP
\fB%!style\fR
Dokumentuan erabiltzeko estilo fitxategia ezartzen du, \-\-style\-k bezala. Adibidez:
.nf
%!style: koloreak.css
.fi



.TP
\fB%!encoding\fR
Dokumentuko karaktere kodeketa adierazteko, \-\-encoding\-ek bezala.  Adibidez:
.nf
%!encoding: UTF-8
.fi



.TP
\fB%!preproc\fR
Iturburu dokumentuko Gorputza aldatzeko erabiltzen den bilatu/ordeztu iragazkia, txt2tags\-ek inolako analisia egin BAINO LEHEN. Bilaketak Python\-eko adierazpen erregularrak erabiltzen ditu. Adibidez:
.nf
%!preproc:  "JJS"  "John J. Smith"
.fi



.TP
\fB%!postproc\fR
Sortutako dokumentua aldatzeko erabiltzen den irteerako bilatu/ordeztu iragazkia, txt2tags\-eko prozesu osoaren ONDOREN. Bilaketak Python\-eko adierazpen erregularrak erabiltzen ditu. Adibidez:
.nf
%!postproc(html):  "<B>"  "<STRONG>"
.fi



.SH KOMANDOAK

.P
Komandoek bihurketa garaian atazak burutzen dituzte. Iturburu dokumentuaren Gorputzean jarri behar dira.

.TP
\fB%!csv: fitxategia.csv\fR
Kanpoko CSV fitxategi bat txertatzen du taula moduan.

.TP
\fB%!include: fitxategia.t2t\fR
Dokumentuan txt2tags fitxategi bat txertatzen du.

.TP
\fB%!include: ``fitxategia.txt``\fR
Dokumentuan testu fitxategi bat txertatzen du (hitzez hitz).

.TP
\fB%!include: fitxategia.html\fR
Dokumentuan dagoeneko etiketatutako fitxategia txertatzen du.

.SH MAKROAK

.P
Makroak zure dokumentuan eduki dinamikoa sartzeko lasterbide baliagarriak dira. Ituruburuko Gorputzean jarri behar dira. %%toc ezik, makro guztiak %Y eta %f bezalako parametro bereziekin pertsonalizatu daitezke. Begiratu txt2tags\-en Erabiltzaile Gida xehetasunetarako.

.TP
\fB%%date\fR
Uneko data txertatzen du. Defektuzko formatua %%date(%Y%m%d) da, UUUUHHEE ematen duena.

.TP
\fB%%infile\fR
Iturburu fitxategiaren bidea txertatzeko. Defektuzko formatua %%infile(%f) da. Dokumentuaren oinean [[Ikusi %%infile iturburua]] bezalako estekak jartzeko erabilgarria.

.TP
\fB%%mtime\fR
Iturburu fitxategiaren aldaketa data txertatzeko. Defektuzko formatua %%mtime(%Y%m%d) da, UUUUHHEE ematen duena.

.TP
\fB%%outfile\fR
Irteerako fitxategiaren bidea txertatzeko. Defektuzko formatua %%outfile(%f) da. "Hau manpage\-eu.man fitxategia da" bezalako aipamenentzako erabilgarria.

.TP
\fB%%toc\fR
Edukien Taula non agertu behar den zehazten du. Behin baino gehiagotan
adieraz dezakezu. Ohartu \-\-toc aukera erabili beharko duzula baita ere.

.SH ADIBIDEAK

.TP
txt2tags \-t html fitx.t2t

HTMLra bihurtu, fitx.html\-n gordez.

.TP
txt2tags \-t html \-o \- fitx.t2t

HTMLra bihurtu, emaitzak STDOUT\-era bidaliz.

.TP
txt2tags \-t html \-\-toc fitx.t2t

HTMLra bihurtu, Edukien Taula automatikoarekin.

.TP
txt2tags \-t html \-\-toc \-\-toc\-level 2 \-n fitx.t2t

HTMLra bihurtu, bi mailatako Edukien Taularekin eta zenbakitutako izenburuekin.

.TP
txt2tags \-\-toc\-only fitx.t2t

Edukien Taula erakutsi bakarrik, bihurketarik egin gabe.

.TP
txt2tags \-t html \-\-css\-sugar \-\-style oinarrizkoa.css \-\-style ui.css fitx.t2t

HTMLra bihurtu, sortutako kodea CSSrekin erabiltzeko prestatuz, eta kanpoko bi CSS fitxategi erabiliz.

.TP
txt2tags \-t art \-\-slides \-\-width 80 \-\-height 25 \-o \- file.t2t | more

Sortu ASCII Art aurkezpen diapositibak, 80x25\-eko terminal/leihoan ikusteko prest.

.TP
(echo ; echo "**bold**") | txt2tags \-t html \-H \-

Lerro bakarreko dei lagungarria STDIN erabiliz froga azkarrak egiteko.

.TP
txt2tags \-t html \-o \- file.t2t | tidy > file.html

Emaitzak STDOUTera bidali eta ondoren kanpoko programa baten bidez txukundu fitxategian gorde baino lehen.

.SH FITXATEGIAK

.TP
~/.txt2tagsrc
Erabiltzailearen defektuzko konfigurazio fitxategia.

.SH INGURUNEA

.TP
T2TCONFIG
Null ez bada, erabiltzailearen defektuzko konfigurazio fitxategiaren bide osoa adierazten du.

.SH EGILEA

.P
Aurelio Jargas <verde@aurelio.net>

.P
Eskuliburu orriaren euskara itzulpena Ales Zabala Alava\-k (Shagi) <shagi@gisa\-elkartea.org> egin du.

.SH ERROREAK

.P
http://bugs.txt2tags.org

.SH COPYRIGHT

.P
Copyright (C) 2001\-2010 Aurelio Jargas, GNU GPL v2

.\" man code generated by txt2tags 2.6 (http://txt2tags.org)
.\" cmdline: txt2tags -t man doc/Basque/manpage-eu.t2t
